---
- hosts: localhost
  become: false
  tasks:
  - name: stop if we have old docker container
    command: sudo docker stop simple-devops-container
    ignore_errors: yes

  - name: remove stopped docker container
    command: sudo docker rm simple-devops-container
    ignore_errors: yes

  - name: remove current docker image
    command: sudo docker rmi simple-devops-image
    ignore_errors: yes

  - name: building docker image
    command: sudo docker build -t simple-devops-image .
    args:
      chdir: hello-world
   
  - name: creating docker image
    command: sudo docker run -d --name simple-devops-container -p 8888:8080 simple-devops-image
